on: push

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.9'

    - name: 'Install dependencies'
      run: |
        npm install
       
    - name: 'Deploy to Azure WebApp Staging'
      if: github.ref == 'refs/heads/staging'
      with: 
        app-name: ${{ secrets.AZURE_STAGING }}
        publish-profile: ${{ secrets.STAGING_PUBLISH_PROFILE }}